src/PCM-LavoroAgile/Controllers/AccordiController.cs
using AutoMapper;
using Domain.Model;
using Domain.Model.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PCM_LavoroAgile.Extensions;
using PCM_LavoroAgile.Models;
using PCM_LavoroAgile.Models.Search;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Domain.ExtensionMethods;
using Domain;
using ObjectsComparer;
using Domain.Model.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json;
using System.IO;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Text;
using System.Net.Http.Headers;
using Domain.Settings;
using Infrastructure.Utils;

namespace PCM_LavoroAgile.Controllers
{
    /// <summary>
    /// Controller per la gestione degli accordi.
    /// </summary>
    [Authorize]
    public class AccordiController : Controller
    {
        private readonly ILogger<AccordiController> _logger;
        private readonly IRepository<Accordo, Guid> _repository;
        private readonly IAccordoService _accordoService;
        private readonly IMapper _mapper;
        private readonly IDocumentsService _documentsService;
        private readonly IStrutturaService _strutturaService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AccordiController(ILogger<AccordiController> logger, 
            IRepository<Accordo, Guid> repository, 
            IAccordoService accordoService, 
            IMapper mapper, 
            IDocumentsService documentsService,
            IStrutturaService strutturaService,
            IWebHostEnvironment webHostEnvironment)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _accordoService = accordoService ?? throw new ArgumentNullException(nameof(accordoService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _documentsService = documentsService ?? throw new ArgumentNullException(nameof(documentsService));
            _strutturaService = strutturaService ?? throw new ArgumentNullException(nameof(strutturaService));
            _webHostEnvironment = webHostEnvironment;
        }

        /// <summary>
        /// Restituisce la pagina con i rultati di ricerca.
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        public IActionResult Index(CancellationToken cancellationToken)
        {
            SearchViewModel searchViewModel = TempData.Get<SearchViewModel>("searchViewModel");
            if (searchViewModel != null)
            {
                ViewData["searchViewModel"] = JsonConvert.SerializeObject(searchViewModel);
                return View(searchViewModel);
            }
            else
            {
                return View(new SearchViewModel());
            }
        }

        /// <summary>
        /// Restituisce una pagina di risultati di ricerca.
        /// </summary>
        /// <param name="searchViewModel">Modello con i parametri di ricerca.</param>
        /// <returns>PartialView con la pagina richiesta.</returns>
        /// <remarks>Questa action viene invocata via Javascript dalla view Index</remarks>
        [Authorize(Policy = "AccordiSearch")]
        public async Task<ActionResult> GetSearchResultPage(SearchViewModel searchViewModel, CancellationToken cancellationToken)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Se il ruolo in parametro non è presente fra quelli dell'utente, solleva eccezione.
                    if (!User.HasClaim(c => c.Type.Equals(searchViewModel.Role, StringComparison.OrdinalIgnoreCase)))
                    {
                        return Forbid();
                    }

                    TempData.Put<SearchViewModel>("searchViewModel", searchViewModel);

                    var searchResults = await _accordoService.FindAsync(User.GetUserId(), searchViewModel.Role, _mapper.Map<AccordoSearch>(searchViewModel), cancellationToken);
                    return PartialView("_SearchResults", new SearchResultCollectionViewModel(
                        searchResults.TotalElements,
                        searchResults.Entities?.Select(a => _mapper.Map<Accordo, AccordoHeaderViewModel>(a, options => options.AfterMap((a, wm) =>
                        {
                            //Se non è una revisione accordo allora si verifica se è un rinnovo
                            if (!a.RevisioneAccordo && a.ValutazioneEsitiAccordoPrecedente != null)
                            {
                                // E' un rinnovo se è valorizzato l'identificativo del padre.
                                wm.IsRinnovo = !Guid.Empty.Equals(a.ParentId);

                                // E' rinnovabile se è un rinnovo, se la data di oggi è antecedente di almeno due settimane 
                                // a quella di scadenza del contratto e se la valutazione c'è ed è positiva
                                wm.Rinnovabile = wm.IsRinnovo && a.ValutazioneEsitiAccordoPrecedente.Equals("Positiva", StringComparison.OrdinalIgnoreCase) && DateTime.UtcNow.Date > a.DataFineAccordoPrecedente.Value.AddDays(-14).Date;
                            }
                        }))).ToList(), role: searchViewModel.Role));
                }

                if (string.IsNullOrWhiteSpace(searchViewModel?.Role))
                {
                    _logger.LogError("Ricerca accordi: ruolo non specificato");
                }

                return null;
            }
            catch (Exception ex)
            {
                _logger.LogError("Ricerca accordi", ex);
                throw new Exception("Errore durante la ricerca");
            }

        }

        /// <summary>
        /// Mostra la pagina di creazione di un accordo
        /// </summary>
        /// <returns></returns>
        /// <remarks>Accesso consentito solo all'utente</remarks>
        [Authorize(policy: "PCM_InternalOperativeRole_Utente")]
        public async Task<IActionResult> Create(CancellationToken cancellationToken)
        {
            var accordoViewModel = _mapper.Map<Accordo, AccordoViewModel>(await _accordoService.InitCreateAccordoAsync(User.GetUserId(), cancellationToken));

            // Automapper popola le date con 01/01/0001, quindi resetta data inizio in modo da evitarne la visualizzazione nella pagina.
            accordoViewModel.DataInizioUtc = null;
            accordoViewModel.DataFineUtc = null;

            await this.GetStruttureForSelect(cancellationToken);

            // Mappa l'accordo al suo view model e lo invia al chiamante.
            return View(accordoViewModel);

        }

        /// <summary>
        /// Crea un accordo.
        /// </summary>
        /// <param name="role">Ruolo utente</param>
        /// <param name="accordoViewModel">View model dell'accordo da creare</param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        /// <remarks>Accesso consentito solo all'utente.</remarks>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(policy: "PCM_InternalOperativeRole_Utente")]
        public async Task<IActionResult> Create(string role, AccordoViewModel accordoViewModel, CancellationToken cancellationToken)
        {
            try
            {
                await this.GetStruttureForSelect(cancellationToken);

                if (ModelState.IsValid)
                {
                    // L'id utente viene comunque ripreso dalla sessione utente
                    Accordo accordo = _mapper.Map<AccordoViewModel, Accordo>(accordoViewModel, opts => opts.BeforeMap((vm, m) => { vm.Dipendente.Id = User.GetUserId(); vm.CreationDate = DateTime.UtcNow; vm.EditTime = DateTime.UtcNow; }));

                    await _accordoService.CreateAccordoAsync(accordo, cancellationToken);

                    TempData.SendNotification(NotificationType.Success, "Accordo salvato correttamente!");

                    return RedirectToAction(nameof(Index), new SearchViewModel { Role = role });
                }
                else
                {
                    TempData.SendNotification(NotificationType.Error, "Campi obbligatori da compilare");
                    return View(nameof(Create), accordoViewModel);
                }
            }
            catch (LavoroAgileException lae)
            {
                TempData.SendNotification(NotificationType.Error, lae.Message);
                return View(nameof(Create), accordoViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError("Crea accordo", ex);
                TempData.SendNotification(NotificationType.Error, "Errore nel salvataggio dell'accordo.");
                return View(nameof(Create), accordoViewModel);
            }
        }

        /// <summary>
        /// Mostra il dettaglio di un accordo.
        /// </summary>
        /// <param name="id">Identificativo dell'accordo</param>
        /// <returns></returns>
        public async Task<ActionResult<AccordoViewModel>> Details(Guid id, string role, CancellationToken cancellationToken)
        {
            AccordoViewModel accordoViewModel = _mapper.Map<AccordoViewModel>(await _accordoService.GetAccordoAsync(id, cancellationToken));
            await this.GetStruttureForSelect(cancellationToken);

            return View(accordoViewModel);
        }

        /// <summary>
        /// Aggiorna il dettaglio di un accordo, nel caso il parametro trasmetti sia treu, effettua anche la tramissione dell'accordo
        /// </summary>
        /// <param name="id">Identificativo dell'accordo da aggiornare.</param>

src/PCM-LavoroAgile/Views/Accordi/Delete.cshtml
@model AccordoHeaderViewModel
@{
    ViewData["Title"] = "Elimina Accordo";
}

<div class="row">
    <div class="col px-lg-2">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/Home">Home</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item">
                    <a href="/Accordi?role=@Context.Request.Query["role"]">Accordi</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item">
                    <a href="/Accordi/Details/@Model.Id?role=@Context.Request.Query["role"]">Dettagli Accordo</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item active">
                    <a href="#">Elimina Accordo</a>
                </li>
            </ol>
        </nav>
    </div>
</div>

<div class="row border-bottom mb-5">
    <div class="col">
        <div class="row">
            <div class="col">
                <h1 class="primary-color">@ViewData["Title"]</h1>
            </div>
        </div>
    </div>
</div>

<form asp-action="Delete" asp-route-role="@Context.Request.Query["role"]">
    <div class="form-row">
        <div class="form-group col" hidden>
            <input type="text" class="form-control" id="id" readonly asp-for="Id">
            <label for="id">Id</label>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <h5>Confermare l'eliminazione dell'accordo Codice: <strong>@Model.DescriptiveCode</strong></h5>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <button type="submit" class="btn btn-primary buttonWidth" onclick="return DisplaySpinner();">Elimina</button>
            @*<a href="/Servizio" class="btn btn-primary buttonWidth" role="button">Indietro</a>*@
            <a href="javascript:void(0);" class="btn btn-primary buttonWidth" role="button" onclick="history.go(-1); return false;">Indietro</a>
        </div>
    </div>
</form>

src/PCM-LavoroAgile/Views/Accordi/Index.cshtml
@model SearchViewModel

<div class="row">
    <div class="col px-lg-2">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="Home">Home</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item active">
                    <a href="#">Risultato della ricerca</a>
                </li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">
                <h1 class="primary-color">Lista degli accordi</h1>
            </div>
        </div>
    </div>
</div>
<div class="row border-top">
    <partial name="_SearchFilters" model="Model" />
    <partial name="_AzioniMassiveDialog" />
    <section class="col-lg-9 py-lg-5 container affix-parent" id="search-resuls-section">
        <div class="d-none d-lg-block d-xl-block affix-top foreground bg-white p-3">
            <div class="row pb-3 px-4 border-bottom">
                <div class="col">
                    <span class="total-results">Ricerca in corso...</span>
                </div>
                <!-- pulsante delle azioni massivie visibile solo ai dirigenti -->
                @if (Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_RESPONSABILE_ACCORDO.ToDescriptionString()) || Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_CAPO_INTERMEDIO.ToDescriptionString()) || Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_CAPO_STRUTTURA.ToDescriptionString()))
                {
                    <div class="auto">
                        <span id="azioni-popover" class="d-inline-block" tabindex="0" data-toggle="popover" data-trigger="hover" data-placement="top" data-html="true" title="Gestisci più accordi" data-content="Selezionare almeno un accordo per attivare il pulsante">
                            <button class="btn btn-sm btn-success buttonWidth" style="pointer-events: none;" id="azioni-massive-input" disabled>Gestisci più accordi</button>
                        </span>
                    </div>

                }
            </div>
        </div>
        <p id="no-results" class="hide"><em>Nessun elemento individuato.</em></p>
        <!-- Risultati ricerca. -->
        <!-- Caricamento risultati -->
        <div id="loading" class="progress progress-indeterminate">
            <span class="sr-only">In caricamento...</span>
            <div class="progress-bar" role="progressbar"></div>
        </div>
    </section>
</div>
@section Scripts {
    <script src="~/lib/jquery-inview/dist/jquery.inview.min.js"></script>
    <script src="~/js/search-manager.js" asp-append-version="true"></script>
    <script src="~/js/azioni-massive.js" asp-append-version="true"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            $(function () {
                $('[data-toggle="popover"]').popover()
            })

            var pageSize = @Model.PageSize;
            var role = getQueryParam('role');
            var fromPage = getQueryParam('fromPage');
            var searchUrl = '@Url.Action("GetSearchResultPage", "Accordi")';    

            // Recupero l'eventuale SearchViewModel dal viewdata per riproporre i filtri di ricerca
            var searchViewModel = '@ViewData["searchViewModel"]'.replace(/&quot;/g,'"');

            // Registrazione del view handler per la gestione della paginazione.
            registerInViewHandler(role, pageSize, '#loading', '.total-results', '#no-results', searchUrl, '#total-search-elements', searchViewModel);

            // Inizializzazione dei filtri.
            initFilters();

            // Inizializzazione del gestore delle selezioni di elementi
            initSelectionManager('#search-resuls-section', role, '#azioni-massive-input', '#azioni-popover');            
        });

    </script>
}

src/PCM-LavoroAgile/Views/Accordi/_AzioniMassiveDialog.cshtml
<div class="modal" tabindex="-1" role="dialog" id="azioni-massive">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Azioni massive</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Chiudi">
                    <svg class="icon">
                        <use xlink:href="/lib/bootstrap-italia/dist/svg/sprite.svg#it-close"></use>
                    </svg>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group pre-scrollable">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Codice</th>
                                <th scope="col">Proponente</th>
                                <th scope="col">Data inizio - Data fine</th>
                            </tr>
                        </thead>
                        <tbody id="accordi-selezionati">
                            <tr>
                                <th scope="row">LA-01</th>
                                <td>Mario Rossi</td>
                                <td>12/12/2021</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div>
                    <div class="form-group">
                        <textarea id="note" name="Note" rows="3" placeholder="Digita qui eventuali note"></textarea>
                        <label for="note">Note</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @if (Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_RESPONSABILE_ACCORDO.ToDescriptionString()))
                {
                    <button class="btn btn-sm btn-success buttonWidth" id="sottoscrivi-input" hidden>Sottoscrivi</button>
                }
                @if (Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_RESPONSABILE_ACCORDO.ToDescriptionString()) || Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_CAPO_INTERMEDIO.ToDescriptionString()) || Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_CAPO_STRUTTURA.ToDescriptionString()))
                {
                    <button id="approva-input" class="btn btn-sm btn-success buttonWidth" hidden>Approva e Sottoscrivi</button>
                    <button id="rifiuta-input" class="btn btn-sm btn-danger buttonWidth" hidden>Rifiuta</button>
                    <button id="modifica-input" class="btn btn-sm btn-info buttonWidth" hidden>Richiedi modifica</button>
                }
                <button class="btn btn-primary btn-sm" type="button" data-dismiss="modal">Chiudi</button>
            </div>
        </div>
    </div>
</div>

src/PCM-LavoroAgile/Views/Accordi/_MoreDetailsDialog.cshtml
@model AccordoViewModel
<div class="modal" tabindex="-1" role="dialog" id="moreDetails-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="title-div">Ulteriori dettagli</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Chiudi">
                    <svg class="icon">
                        <use xlink:href="/lib/bootstrap-italia/dist/svg/sprite.svg#it-close"></use>
                    </svg>
                </button>
            </div>
            <div class="modal-body">
                <div id="divModalBodyPianificazioneDate" class="form-group">
                    <label class="active">Pianificazione date</label>
                    <textarea id="pianificazioneDate" name="pianificazioneDate" placeholder=" " rows="5" style="overflow-y:auto">@Model.PianificazioneDateAccordo</textarea>
                </div>
                <div id="divModalBodyFasceContattabilita" class="form-group">
                    <label class="active">Fasce di contattabilità</label>
                    @{string fasceContattabilita = string.Join(",", Model.FasceDiContattabilita);}
                    <textarea id="fasceContattabilita" name="fasceContattabilita" placeholder=" " rows="5" style="overflow-y:auto">@fasceContattabilita</textarea>
                </div>
                <div id="divModalBodyValutazione" class="form-group">
                    <p><label class="active">Valutazione</label></p>
                    <div class="table-responsive">
                        <table id="tableValutazione" class="table">
                            <tbody>
                                @foreach (AttivitaAccordoViewModel attivitaAccordoViewModel in Model.ListaAttivita)
                                {
                                    <partial name="../Valutazioni/_AttivitaAccordoPartialDetailsReadOnly" model="attivitaAccordoViewModel" />                                    
                                }
                            </tbody>
                        </table>
                    </div>

                    <div class="form-row active" style="margin-top:50px">
                        <div class="col">
                            <textarea id="NotaDipendente" class="text-primary" readonly>@(String.IsNullOrEmpty(Model.NotaDipendente) ? "Nessuna nota" : Model.NotaDipendente)</textarea>
                            <label for="NotaDipendente" class="active">Note del Dipendente - @(Model.DataNotaDipendente.HasValue ? Model.DataNotaDipendente.Value.ToString("dd/MM/yyyy") : "[n/a]")</label>
                        </div>
                    </div>
                        
                    <div class="form-row" style="margin-top:50px">
                        <div class="col">                            
                            <textarea id="NotaDirigente" class="text-primary" readonly>@(String.IsNullOrEmpty(Model.NotaDirigente) ? "Nessuna nota" : Model.NotaDirigente)</textarea>                   
                            <label for="NotaDirigente" class="active">Note del Dirigente - @(Model.DataNotaDirigente.HasValue ? Model.DataNotaDirigente.Value.ToString("dd/MM/yyyy") : "[n/a]")</label>
                        </div>
                    </div>

                    <a class="btn btn-primary btn-sm" target="_blank" href="@Url.Action("GeneratePdfValutazione", "Accordi", new { id = Model.Id })">Download valutazione</a>
                </div>
            </div>
            <div class="modal-footer">                
                <button class="btn btn-primary btn-sm" type="button" data-dismiss="modal">Chiudi</button>
            </div>
        </div>
    </div>
</div>

src/PCM-LavoroAgile/Views/Accordi/_SearchResults.cshtml
@using PCM_LavoroAgile.Extensions;
@model SearchResultCollectionViewModel

<input type="hidden" id="total-search-elements" value="@Model.TotalElements" />
@foreach (var result in Model.SearchResults)
{
    <div class="row">
        <div class="col">
            <div class="card card-teaser">
                <div class="card-body">
                    <div class="row">
                        <!-- Colonna di selezione multipla mostrata solo se utente è dirigente -->
                        @if (Model.Role.Equals(RoleAndKeysClaimEnum.KEY_CLAIM_RESPONSABILE_ACCORDO.ToDescriptionString()) || Model.Role.Equals(RoleAndKeysClaimEnum.KEY_CLAIM_CAPO_INTERMEDIO.ToDescriptionString()) || Model.Role.Equals(RoleAndKeysClaimEnum.KEY_CLAIM_CAPO_STRUTTURA.ToDescriptionString()))
                        {
                            <div class="col-1">
                                <div class="form-check">
                                    <input id="@result.Id" type="checkbox" data-isresponsabileaccordo="@result.IdResponsabileAccordo.Equals(User.GetUserId())">
                                    <label for="@result.Id"></label>
                                </div>
                            </div>
                        }
                    <div class="col auto">
                        <input type="hidden" id="is-rinnovo-input" value="@result.IsRinnovo" />
                        <input type="hidden" id="rinnovabile-input" value="@result.Rinnovabile" />

                        <div class="category-top">
                            <svg class="icon">
                                <use xlink:href="/lib/bootstrap-italia/dist/svg/sprite.svg#it-file"></use>
                            </svg>
                        </div>
                        <div class="row">
                            <div class="col">
                                <strong>Codice:</strong> <span class="@(result.DataSottoscrizione.HasValue ? "text-primary" : "text-danger font-italic")" id="codice">@result.DescriptiveCode</span>
                            </div>
                            <div class="col">
                                <strong>Responsabile accordo:</strong> @result.ResponsabileAccordo
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <strong>Proponente:</strong> <span id="proponente">@result.NomeCognome</span>
                            </div>
                            <div class="col">
                                <strong>Capo intermedio:</strong> @result.CapoIntermedio
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <strong>Data inizio:</strong> <span id="data-inizio">@result.DataInizioUtc.ToString("dd MMMM yyyy")</span>
                            </div>
                            <div class="col">
                                <strong>Capo struttura:</strong> @result.CapoStruttura
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <strong>Data fine:</strong> <span id="data-fine">@result.DataFineUtc.ToString("dd MMMM yyyy")</span>
                            </div>
                            @if(result.isValutazionePositiva)
                            {
                                <div class="col">
                                    <strong>Valutazione:</strong> Positiva
                                </div>
                            }
                            @if(!result.isValutazionePositiva && result.DataNotaDipendente != null && result.DataNotaDirigente != null)
                            {
                                <div class="col">
                                    <strong>Valutazione:</strong> Negativa
                                </div>       
                            }
                            @if(!result.isValutazionePositiva && result.DataNotaDipendente != null && result.DataNotaDirigente == null)
                            {
                                <div class="col">
                                    <strong>Valutazione:</strong> In attesa di valutazione
                                </div>   
                            }
                            @if ((result.Stato == StatoAccordo.Sottoscritto || result.Stato == StatoAccordo.Recesso || result.Stato == StatoAccordo.AccordoConcluso) &&
                                 Context.Request.Query["role"].Equals(RoleAndKeysClaimEnum.KEY_CLAIM_UTENTE.ToDescriptionString()) && 
                                result.DataNotaDipendente == null && 
                                result.DataFineUtc.AddDays(-10) <= DateTime.UtcNow
                                )
                            {
                                <div class="col">
                                    <strong>Valutazione:</strong> Valutazione da richiedere
                                </div>
                            }
                            </div>
                         @if (result.Stato == StatoAccordo.Bozza ||
                                result.Stato == StatoAccordo.Sottoscritto ||
                                result.Stato == StatoAccordo.DaApprovareRA ||
                                result.Stato == StatoAccordo.DaApprovareCI ||
                                result.Stato == StatoAccordo.DaApprovareCS ||
                                result.Stato == StatoAccordo.DaSottoscrivereP ||
                                result.Stato == StatoAccordo.DaSottoscrivereRA)
                            {
                                <div class="row">
                                    <div class="col">
                                        <a class="text-decoration-none font-weight-bold" target="_blank" href="@Url.Action("GeneratePdf", "Accordi", new { id = @result.Id })"><i>Download accordo</i></a>
                                    </div>
                                </div>
                            }
                            <div class="row">
                            <div class="col">

                                <p class="text-uppercase font-italic primary-color-c9" id="stato" data-codice-stato="@result.Stato">
                                    <span>@result.Stato.ToDescriptionString() </span>
                                    @if (result.InCorso && result.Stato != StatoAccordo.RecessoPianificato && result.Stato == StatoAccordo.Sottoscritto)
                                    {
                                        <span class="text-success">
                                            (In Corso dal @result.DataInizioUtc.Date.ToShortDateString() al @result.DataFineUtc.Date.ToShortDateString())
                                        </span>
                                    }
                                    @if (result.Stato == StatoAccordo.RecessoPianificato && result.DataRecesso.HasValue)
                                    {
                                        <span class="text-success">
                                            (In Corso fino al @result.DataRecesso.Value.Date.ToShortDateString())
                                        </span>
                                    }
                                </p>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col">

                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <a class="text-decoration-none font-weight-bold" href="@Url.Action("Details", "Accordi", new { id = @result.Id, role = Model.Role })">Vai al dettaglio</a>
                            </div>
                        </div>
                    </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}