src/PCM-LavoroAgile/Models/StrutturaViewModel.cs
using Infrastructure.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PCM_LavoroAgile.Models
{
    public class StrutturaViewModel : IValidatableObject
    {
        public Guid Id { get; set; }

        public string Author { get; set; }

        public DateTime CreationDate { get; set; }

        public DateTime EditTime { get; set; }

        public byte[] Timestamp { get; set; }

        public string StrutturaCompleta { get; set; }

        public string StrutturaLiv1 { get; set; }

        public string StrutturaLiv2 { get; set; }

        public string StrutturaLiv3 { get; set; }

        public bool DirettaCollaborazione { get; set; }

        public DirigenteViewModel CapoStruttura { get; set; }

        public DirigenteViewModel CapoIntermedio { get; set; }

        public DirigenteViewModel DirigenteResponsabile { get; set; }

        public DirigenteViewModel ResponsabileAccordo { get; set; }

        public ReferenteViewModel ReferenteInterno { get; set; }

        /// <summary>
        /// Strutture gestite con una integrazione esterna, solo primo livello = true
        /// Strutture gestite internamente da db, solo primo livello = false
        /// </summary>
        public bool OnlyFirstLevel { get; set; } = false;

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if(OnlyFirstLevel)
            {
                //Se le strutture sono gestite son una integrazione esterna,
                //va verificata solo l'obbligatorietà della struttura di primo livello e dei dati del referente interno
                if (string.IsNullOrWhiteSpace(StrutturaLiv1))
                    yield return new ValidationResult("Campo obbligatorio", new[] { nameof(StrutturaLiv1) });
                
                //Per motivi organizzativi al momento l'obbligatorietà del referente interno è stata rilassata
                //if (string.IsNullOrWhiteSpace(ReferenteInterno))
                //    yield return new ValidationResult("Campo obbligatorio", new[] { nameof(ReferenteInterno) });
                //if (string.IsNullOrWhiteSpace(EmailReferenteInterno))
                //    yield return new ValidationResult("Campo obbligatorio", new[] { nameof(EmailReferenteInterno) });
                //if(!RegexUtilities.IsValidEmail(EmailReferenteInterno))
                //    yield return new ValidationResult("Inserire una email valida", new[] { nameof(EmailReferenteInterno) });
            }
            else
            {
                //Se le strutture sono gestine internamente, vanno verificati tutte le obbligatorietà

                //Livello 1, Dati capo struttura, Dati responsabile accordo e Dati Referente interno sono obbligatori
                if (string.IsNullOrWhiteSpace(StrutturaLiv1))
                    yield return new ValidationResult("Campo obbligatorio", new[] { nameof(StrutturaLiv1) });

                if (string.IsNullOrWhiteSpace(CapoStruttura?.NomeCognome))
                    yield return new ValidationResult("Campo obbligatorio", new[] { $"{nameof(CapoStruttura)}.{nameof(CapoStruttura.NomeCognome)}" });
                if (string.IsNullOrWhiteSpace(CapoStruttura?.Email))
                    yield return new ValidationResult("Campo obbligatorio", new[] { $"{nameof(CapoStruttura)}.{nameof(CapoStruttura.Email)}" });
                if (!RegexUtilities.IsValidEmail(CapoStruttura?.Email))
                    yield return new ValidationResult("Inserire una email valida", new[] { $"{nameof(CapoStruttura)}.{nameof(CapoStruttura.Email)}" });

                if (!string.IsNullOrWhiteSpace(StrutturaLiv2))
                {
                    if (string.IsNullOrWhiteSpace(CapoIntermedio?.NomeCognome))
                        yield return new ValidationResult("Campo obbligatorio", new[] { $"{nameof(CapoIntermedio)}.{nameof(CapoIntermedio.NomeCognome)}" });
                    if (string.IsNullOrWhiteSpace(CapoStruttura?.Email))
                        yield return new ValidationResult("Campo obbligatorio", new[] { $"{nameof(CapoIntermedio)}.{nameof(CapoIntermedio.Email)}" });
                    if (!RegexUtilities.IsValidEmail(CapoStruttura?.Email))
                        yield return new ValidationResult("Inserire una email valida", new[] { $"{nameof(CapoIntermedio)}.{nameof(CapoIntermedio.Email)}" });
                }

                if (string.IsNullOrWhiteSpace(ResponsabileAccordo?.NomeCognome))
                    yield return new ValidationResult("Campo obbligatorio", new[] { $"{nameof(ResponsabileAccordo)}.{nameof(ResponsabileAccordo.NomeCognome)}" });
                if (string.IsNullOrWhiteSpace(ResponsabileAccordo?.Email))
                    yield return new ValidationResult("Campo obbligatorio", new[] { $"{nameof(ResponsabileAccordo)}.{nameof(ResponsabileAccordo.Email)}" });
                if (!RegexUtilities.IsValidEmail(ResponsabileAccordo?.Email))
                    yield return new ValidationResult("Inserire una email valida", new[] { $"{nameof(ResponsabileAccordo)}.{nameof(ResponsabileAccordo.Email)}" });

                //Per motivi organizzativi al momento l'obbligatorietà del referente interno è stata rilassata
                //if (string.IsNullOrWhiteSpace(ReferenteInterno))
                //    yield return new ValidationResult("Campo obbligatorio", new[] { nameof(ReferenteInterno) });
                //if (string.IsNullOrWhiteSpace(EmailReferenteInterno))
                //    yield return new ValidationResult("Campo obbligatorio", new[] { nameof(EmailReferenteInterno) });
                //if (!RegexUtilities.IsValidEmail(EmailReferenteInterno))
                //    yield return new ValidationResult("Inserire una email valida", new[] { nameof(EmailReferenteInterno) });                
            }            
        }
    }
}

src/PCM-LavoroAgile/Controllers/StrutturaController.cs
using AutoMapper;
using Domain.Model;
using Infrastructure.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using PCM_LavoroAgile.Extensions;
using PCM_LavoroAgile.Models;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace PCM_LavoroAgile.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StrutturaController : Controller
    {
        private readonly ILogger<StrutturaController> _logger;
        private readonly IStrutturaService _strutturaService;
        private readonly IMapper _mapper;

        public StrutturaController(ILogger<StrutturaController> logger,
                IStrutturaService strutturaService,
                IMapper mapper)
        {
            _strutturaService = strutturaService;
            _logger = logger;
            _mapper = mapper;
        }

        [ResponseCache(NoStore = true, VaryByHeader = "None", Duration = 0)]
        public async Task<ActionResult> Index(string filter, CancellationToken cancellationToken, int pageIndex = 1)
        {
            IOrderedQueryable<StrutturaViewModel> listaStrutture = (await _strutturaService.FindStrutturaAsync(cancellationToken: cancellationToken)).Entities.Select(s => _mapper.Map<StrutturaViewModel>(s)).AsQueryable().OrderBy(s => s.StrutturaCompleta);

            if (!string.IsNullOrWhiteSpace(filter))
                listaStrutture = listaStrutture.Where(s => s.StrutturaCompleta.Contains(filter, StringComparison.InvariantCultureIgnoreCase)).OrderBy(s => s.StrutturaCompleta);
            
            var model = PagingList.Create<StrutturaViewModel>(listaStrutture, 10, pageIndex);
            model.RouteValue = new RouteValueDictionary { { "filter", filter} };

            return View(model);            
        }

        public async Task<IActionResult> AutocompleteLivelloStruttura(string term, string livello, CancellationToken cancellationToken)
        {
            try
            {
                List<string> searchResult = new List<string>();

                switch (livello)
                {
                    case "StrutturaLiv1":
                        searchResult = (await _strutturaService.FindStrutturaAsync(s => s.StrutturaLiv1 != null && s.StrutturaLiv1.ToUpper().Contains(term.ToUpper()), cancellationToken: cancellationToken))
                            .Entities.Select(s => s.StrutturaLiv1).Distinct().ToList();
                        break;

                    case "StrutturaLiv2":
                        searchResult = (await _strutturaService.FindStrutturaAsync(s => s.StrutturaLiv2 != null && s.StrutturaLiv2.ToUpper().Contains(term.ToUpper()), cancellationToken: cancellationToken))
                            .Entities.Select(s => s.StrutturaLiv2).Distinct().ToList();
                        break;

                    case "StrutturaLiv3":
                            searchResult = (await _strutturaService.FindStrutturaAsync(s => s.StrutturaLiv3 != null && s.StrutturaLiv3.ToUpper().Contains(term.ToUpper()), cancellationToken: cancellationToken))
                            .Entities.Select(s => s.StrutturaLiv3).Distinct().ToList();
                        break;
                }                

                return Json(searchResult);
            }
            catch (Exception)
            {
                return null;
            }
        }

        public async Task<IActionResult> Create()
        {
            try
            {
                StrutturaViewModel strutturaViewModel = _mapper.Map<Struttura, StrutturaViewModel>(await _strutturaService.InitCreateStrutturaAsync());
                return View(strutturaViewModel);
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(StrutturaViewModel strutturaViewModel, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Struttura struttura = _mapper.Map<StrutturaViewModel, Struttura>(strutturaViewModel, opts => opts.BeforeMap((vm, m) => { vm.Author = User.Identity.Name; vm.CreationDate = DateTime.UtcNow; vm.EditTime = DateTime.UtcNow; vm.DirigenteResponsabile = vm.ResponsabileAccordo; }));

                    await _strutturaService.InsertStrutturaAsync(struttura, cancellationToken);

                    TempData.SendNotification(NotificationType.Success, "Struttura salvata correttamente!");
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    TempData.SendNotification(NotificationType.Error, "Si è verificato un errore non identificato durante il salvataggio");
                    return View(strutturaViewModel);
                }
            }
            else
            {
                TempData.SendNotification(NotificationType.Error, "Campi obbligatori da compilare");
                return View("Create", strutturaViewModel);
            }    
        }

        public async Task<IActionResult> Details(Guid id, CancellationToken cancellationToken)
        {
            try
            {
                StrutturaViewModel strutturaViewModel = (_mapper.Map<Struttura, StrutturaViewModel>(await _strutturaService.GetStrutturaAsync(id, cancellationToken)));
                return View(strutturaViewModel);
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, [Bind] StrutturaViewModel strutturaViewModel, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Struttura struttura = _mapper.Map<StrutturaViewModel, Struttura>(strutturaViewModel, opts => opts.BeforeMap((vm, m) => { vm.Author = User.Identity.Name; vm.CreationDate = DateTime.UtcNow; vm.EditTime = DateTime.UtcNow; }));

                    await _strutturaService.UpdateStrutturaAsync(struttura, cancellationToken);

                    TempData.SendNotification(NotificationType.Success, "Struttura salvata correttamente!");
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    TempData.SendNotification(NotificationType.Error, "Si è verificato un errore non identificato durante il salvataggio delle modifiche");
                    return View("Details", strutturaViewModel);
                }
            }
            else
            {
                TempData.SendNotification(NotificationType.Error, "Campi obbligatori da compilare");
                return View("Details", strutturaViewModel);
            }
        }

        public async Task<ActionResult> Delete(Guid id, CancellationToken cancellationToken)
        {
            try
            {
                return View(_mapper.Map<StrutturaViewModel>(await _strutturaService.GetStrutturaAsync(id, cancellationToken)));
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeletePost(Guid id, CancellationToken cancellationToken)
        {
            try
            {
                await _strutturaService.DeleteStrutturaAsync(id, cancellationToken);

                TempData.SendNotification(NotificationType.Success, "Struttura eliminata correttamente!");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

src/PCM-LavoroAgile/Views/Struttura/Create.cshtml
@model StrutturaViewModel
@{
    ViewData["Title"] = "Nuova Struttura";
}

<div class="row">
    <div class="col px-lg-2">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/Home">Home</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item active">
                    <a href="#">Struttura PCM - Nuova Struttura</a>
                </li>
            </ol>
        </nav>
    </div>
</div>

<div class="row border-bottom mb-5">
    <div class="col">
        <div class="row">
            <div class="col">
                <h1 class="primary-color">@ViewData["Title"]</h1>
            </div>
        </div>
    </div>
</div>

<form asp-action="Create" id="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <!--Hidden-->
    @Html.HiddenFor(s => s.Id)
    
    @Html.HiddenFor(s => s.OnlyFirstLevel)  
    <!--Hidden-->

    <h4 class="primary-color">Primo livello</h4>
    <hr />
    <div class="form-row">
        <div class="form-group col">
            <input type="text" class="form-control" id="StrutturaLiv1" asp-for="StrutturaLiv1" data-set-responsabile>
            <label for="StrutturaLiv1">Struttura primo livello</label>
            <span asp-validation-for="StrutturaLiv1" class="text-danger"></span>
        </div>
    </div>

    <div id="struttura-complete" hidden="@Model.OnlyFirstLevel">        
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="CapoStruttura" asp-for="CapoStruttura.NomeCognome" data-set-responsabile>
                <label for="CapoStruttura">Capo struttura</label>
                <span asp-validation-for="CapoStruttura.NomeCognome" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <input type="text" class="form-control" id="EmailCapoStruttura" asp-for="CapoStruttura.Email" data-set-responsabile>
                <label for="EmailCapoStruttura">Email Capo struttura</label>
                <span asp-validation-for="CapoStruttura.Email" class="text-danger"></span>
            </div>
        </div>

        <h4 class="primary-color">Secondo livello</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="StrutturaLiv2" asp-for="StrutturaLiv2" data-set-responsabile>
                <label for="StrutturaLiv2">Struttura secondo livello</label>
                <span asp-validation-for="StrutturaLiv2" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="CapoIntermedio" asp-for="CapoIntermedio.NomeCognome" data-set-responsabile>
                <label for="CapoIntermedio">Capo intermedio</label>
                <span asp-validation-for="CapoIntermedio.NomeCognome" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <input type="text" class="form-control" id="EmailCapoIntermedio" asp-for="CapoIntermedio.Email" data-set-responsabile>
                <label for="EmailCapoIntermedio">Email Capo intermedio</label>
                <span asp-validation-for="CapoIntermedio.Email" class="text-danger"></span>
            </div>
        </div>

        <h4 class="primary-color">Terzo livello</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="StrutturaLiv3" asp-for="StrutturaLiv3" data-set-responsabile>
                <label for="StrutturaLiv3">Struttura terzo livello</label>
                <span asp-validation-for="StrutturaLiv3" class="text-danger"></span>
            </div>
        </div>    

        <h4 class="primary-color">Responsabile accordo</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="ResponsabileAccordo" asp-for="ResponsabileAccordo.NomeCognome">
                <label for="ResponsabileAccordo" class="active">Responsabile accordo</label>
                <span asp-validation-for="ResponsabileAccordo.NomeCognome" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <input type="text" class="form-control" id="EmailResponsabileAccordo" asp-for="ResponsabileAccordo.Email">
                <label for="EmailResponsabileAccordo" class="active">Email Responsabile accordo</label>
                <span asp-validation-for="ResponsabileAccordo.Email" class="text-danger"></span>
            </div>
        </div>
    </div>

    <!--
        La diretta collaborazione non è al momento gestita 
        Il dirigente responsabile si è deciso che coincida con il responsabile dell'accordo
    -->
    @*
    <div class="form-row">
        <div class="form-group col form-check">
            <input type="checkbox" id="DirettaCollaborazione" asp-for="DirettaCollaborazione">
            <label for="DirettaCollaborazione">Diretta collaborazione</label>
            <span asp-validation-for="DirettaCollaborazione" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <input type="text" class="form-control" id="DirigenteResponsabile" asp-for="DirigenteResponsabile" data-set-responsabile>
            <label for="DirigenteResponsabile">Dirigente responsabile</label>
            <span asp-validation-for="DirigenteResponsabile" class="text-danger"></span>
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" id="EmailDirigenteResponsabile" asp-for="EmailDirigenteResponsabile" data-set-responsabile>
            <label for="EmailDirigenteResponsabile">Email Dirigente responsabile</label>
            <span asp-validation-for="EmailDirigenteResponsabile" class="text-danger"></span>
        </div>
    </div>
    *@

    <h4 class="primary-color">Referente interno</h4>
    <hr />   

    <div class="form-row">
        <div class="form-group col">
            <input type="text" class="form-control" id="ReferenteInterno" asp-for="ReferenteInterno.NomeCognome">
            <label for="ReferenteInterno">Referente interno</label>
            <span asp-validation-for="ReferenteInterno.NomeCognome" class="text-danger"></span>
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" id="EmailReferenteInterno" asp-for="ReferenteInterno.Email">
            <label for="EmailReferenteInterno">Email Referente interno</label>
            <span asp-validation-for="ReferenteInterno.Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <button type="submit" class="btn btn-primary buttonWidth" onclick="return DisplaySpinner();">Salva</button>
            @*<a href="/Servizio" class="btn btn-primary buttonWidth" role="button">Indietro</a>*@
            <a href="javascript:void(0);" class="btn btn-primary buttonWidth" role="button" onclick="history.go(-1); return false;">Indietro</a>
        </div>
    </div>

</form>

@section Scripts {
    <script>
        initStruttura('@Url.Action("AutocompleteLivelloStruttura", "Struttura")');
    </script>
}

src/PCM-LavoroAgile/Views/Struttura/Details.cshtml
@model StrutturaViewModel
@{
    ViewData["Title"] = "Dettaglio Struttura";
}

<div class="row">
    <div class="col px-lg-2">
        <nav class="breadcrumb-container" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/Home">Home</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item">
                    <a href="/Struttura/Index">Lista Strutture</a><span class="separator">/</span>
                </li>
                <li class="breadcrumb-item active">
                    <a href="#">Struttura PCM - Dettaglio Struttura</a>
                </li>
            </ol>
        </nav>
    </div>
</div>

<div class="row border-bottom mb-5">
    <div class="col">
        <div class="row">
            <div class="col">
                <h1 class="primary-color">@ViewData["Title"]</h1>
            </div>
        </div>
    </div>
</div>

<form asp-action="Edit" id="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    
    <!--Hidden-->
    @Html.HiddenFor(s => s.Id)
    @Html.HiddenFor(s => s.Timestamp)
    @Html.HiddenFor(s => s.Author)
    @Html.HiddenFor(s => s.CreationDate)
    @Html.HiddenFor(s => s.EditTime)
    @Html.HiddenFor(s => s.DirigenteResponsabile.NomeCognome)
    @Html.HiddenFor(s => s.DirigenteResponsabile.Email)
   
    @Html.HiddenFor(s => s.OnlyFirstLevel)
    <!--Hidden-->

    <div class="form-row">
        <div class="form-group col">
            <input type="text" class="form-control" id="StrutturaCompleat" asp-for="StrutturaCompleta" data-set-responsabile readonly>
            <label for="StrutturaLiv1">Struttura completa</label>
            <span asp-validation-for="StrutturaCompleta" class="text-danger"></span>
        </div>
    </div>

    <div id="struttura-complete" hidden="@Model.OnlyFirstLevel">
        <h4 class="primary-color">Primo livello</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="StrutturaLiv1" asp-for="StrutturaLiv1" data-set-responsabile readonly>
                <label for="StrutturaLiv1">Struttura primo livello</label>
                <span asp-validation-for="StrutturaLiv1" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="CapoStruttura" asp-for="CapoStruttura.NomeCognome" data-set-responsabile>
                <label for="CapoStruttura">Capo struttura</label>
                <span asp-validation-for="CapoStruttura.NomeCognome" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <input type="text" class="form-control" id="EmailCapoStruttura" asp-for="CapoStruttura.Email" data-set-responsabile>
                <label for="EmailCapoStruttura">Email Capo struttura</label>
                <span asp-validation-for="CapoStruttura.Email" class="text-danger"></span>
            </div>
        </div>

        <h4 class="primary-color">Secondo livello</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="StrutturaLiv2" asp-for="StrutturaLiv2" data-set-responsabile>
                <label for="StrutturaLiv2">Struttura secondo livello</label>
                <span asp-validation-for="StrutturaLiv2" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="CapoIntermedio" asp-for="CapoIntermedio.NomeCognome" data-set-responsabile>
                <label for="CapoIntermedio">Capo intermedio</label>
                <span asp-validation-for="CapoIntermedio.NomeCognome" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <input type="text" class="form-control" id="EmailCapoIntermedio" asp-for="CapoIntermedio.Email" data-set-responsabile>
                <label for="EmailCapoIntermedio">Email Capo intermedio</label>
                <span asp-validation-for="CapoIntermedio.Email" class="text-danger"></span>
            </div>
        </div>

        <h4 class="primary-color">Terzo livello</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="StrutturaLiv3" asp-for="StrutturaLiv3" data-set-responsabile>
                <label for="StrutturaLiv3">Struttura terzo livello</label>
                <span asp-validation-for="StrutturaLiv3" class="text-danger"></span>
            </div>
        </div>

        <h4 class="primary-color">Responsabile accordo</h4>
        <hr />
        <div class="form-row">
            <div class="form-group col">
                <input type="text" class="form-control" id="ResponsabileAccordo" asp-for="ResponsabileAccordo.NomeCognome">
                <label for="ResponsabileAccordo">Responsabile accordo</label>
                <span asp-validation-for="ResponsabileAccordo.NomeCognome" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <input type="text" class="form-control" id="EmailResponsabileAccordo" asp-for="ResponsabileAccordo.Email">
                <label for="EmailResponsabileAccordo">Email Responsabile accordo</label>
                <span asp-validation-for="ResponsabileAccordo.Email" class="text-danger"></span>
            </div>
        </div>
    </div>

    <!--
        La diretta collaborazione non è al momento gestita 
        Il dirigente responsabile si è deciso che coincida con il responsabile dell'accordo
    -->
    @*
    <div class="form-row">
        <div class="form-group col form-check">
            <input type="checkbox" id="DirettaCollaborazione" asp-for="DirettaCollaborazione">
            <label for="DirettaCollaborazione">Diretta collaborazione</label>
            <span asp-validation-for="DirettaCollaborazione" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col">
            <input type="text" class="form-control" id="DirigenteResponsabile" asp-for="DirigenteResponsabile" placeholder="Nome responsabile accordo" data-set-responsabile>
            <label for="DirigenteResponsabile">Dirigente responsabile</label>
            <span asp-validation-for="DirigenteResponsabile" class="text-danger"></span>
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" id="EmailDirigenteResponsabile" asp-for="EmailDirigenteResponsabile" placeholder="Nome responsabile accordo" data-set-responsabile>
            <label for="EmailDirigenteResponsabile">Email Dirigente responsabile</label>
            <span asp-validation-for="EmailDirigenteResponsabile" class="text-danger"></span>
        </div>
    </div>
    *@

    <h4 class="primary-color">Referente interno</h4>
    <hr />

    <div class="form-row">
        <div class="form-group col">
            <input type="text" class="form-control" id="ReferenteInterno" asp-for="ReferenteInterno.NomeCognome">
            <label for="ReferenteInterno">Referente interno</label>
            <span asp-validation-for="ReferenteInterno.NomeCognome" class="text-danger"></span>
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" id="EmailReferenteInterno" asp-for="ReferenteInterno.Email">
            <label for="EmailReferenteInterno">Email Referente interno</label>
            <span asp-validation-for="ReferenteInterno.Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <button type="submit" class="btn btn-primary buttonWidth" onclick="return DisplaySpinner();">Aggiorna</button>
            @*<a href="/Servizio" class="btn btn-primary buttonWidth" role="button">Indietro</a>*@
            <a href="javascript:void(0);" class="btn btn-primary buttonWidth" role="button" onclick="history.go(-1); return false;">Indietro</a>
        </div>
    </div>
</form>

@section Scripts {
    <script>
        initStruttura('@Url.Action("AutocompleteLivelloStruttura", "Struttura")');

    </script>
}